# Generated by Django 5.2.8 on 2026-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCheckpointMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('horizon', models.CharField(max_length=16)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('rolling_mae', models.FloatField(blank=True, null=True)),
                ('learning_rate', models.FloatField(default=0.05)),
            ],
            options={
                'unique_together': {('ticker', 'horizon')},
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=16)),
                ('horizon', models.CharField(max_length=16)),
                ('predicted_at', models.DateTimeField(db_index=True)),
                ('target_at', models.DateTimeField()),
                ('base_price', models.FloatField()),
                ('predicted_return', models.FloatField()),
                ('predicted_price', models.FloatField()),
                ('naive_return', models.FloatField(default=0.0)),
                ('rw_sigma', models.FloatField(default=0.0)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('actual_return', models.FloatField(blank=True, null=True)),
                ('error', models.FloatField(blank=True, null=True)),
                ('abs_error', models.FloatField(blank=True, null=True)),
                ('hit', models.BooleanField(blank=True, null=True)),
                ('naive_abs_error', models.FloatField(blank=True, null=True)),
                ('naive_hit', models.BooleanField(blank=True, null=True)),
                ('rw_abs_error', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(default='live', max_length=16)),
            ],
            options={
                'ordering': ['-predicted_at'],
                'indexes': [models.Index(fields=['ticker', 'horizon', 'predicted_at'], name='rl_engine_p_ticker_e918de_idx'), models.Index(fields=['ticker', 'horizon', 'resolved'], name='rl_engine_p_ticker_961bc0_idx')],
            },
        ),
    ]
